---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: https://github.com/cristian04/dotfiles-1.git
dotfiles_repo_accept_hostkey: yes 
dotfiles_repo_local_destination: ~/dotfiles-ansible
dotfiles_files: []
homebrew_clear_cache: true
homebrew_installed_packages:
- asciinema
- asdf
- awscli
- axel
- cmatrix
- coreutils
- cowsay
- docker-machine
- docker-machine-driver-hyperkit
- docker-machine-driver-xhyve
- figlet
- findutils
- git
- git-lfs
- go
- grep
- helm@2
- hostess
- iftop
- jq
- kompose
- kubernetes-cli
- kubernetes-helm
- kube-ps1
- mas
- midnight-commander
- minikube
- moreutils
- node
- p7zip
- pandoc
- screen
- ssh-copy-id
- sshuttle
- tcpflow
- tree
- tmux
- unrar
- velero
- watch
- wget
- youtube-dl
  

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - brave-browser
  - cakebrew
  - coconutbattery
  - docker
  - google-cloud-sdk
  - gpg-suite
  - iina
  - iterm2
  - slack
  - spotify
  - spotify-notifications
  - sublime-text
  - vagrant
  - virtualbox
  - visual-studio-code
  
# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
- { id: 1147396723, name: "WhatsApp (0.4.316)" }
- { id: 682658836, name: "GarageBand (10.3.2)" }
- { id: 408981434, name: "iMovie (10.1.14)" }
- { id: 803453959, name: "Slack (4.2.0)" }
- { id: 406825478, name: "Telephone (1.4)" }
- { id: 497799835, name: "Xcode (11.3.1)" }
- { id: 406056744, name: "Evernote (7.14)" }

mas_email: ""
mas_password: ""
mas_signin_dialog: no

osx_script: "~/dotfiles-ansible/.macos" #Just the hacker sensitive stuff

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: gtop
    state: present # present/absent/latest, default: present
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

