---
downloads: ~/.ansible-downloads/

configure_dotfiles: no
configure_sudoers: no
configure_terminal: no
configure_osx: yes

dotfiles_repo: git@github.com:cristian04/dotfiles-1.git
dotfiles_repo_accept_hostkey: yes 
dotfiles_repo_local_destination: ~/dotfiles-ansible
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  
homebrew_clear_cache: true
homebrew_installed_packages:
  - ack
  - arp-scan
  - asciinema
  - asdf
  - awscli
  - axel
  - bash
  - bash-completion2
  - binwalk
  - cmatrix
  - coreutils
  - cowsay
  - docker-machine
  - docker-machine-driver-hyperkit
  - ext4fuse
  - ffmpeg
  - figlet
  - findutils
  - flow
  - fontconfig
  - fortune
  - gettext
  - git
  - git-lfs
  - gnupg
  - gnuplot
  - go
  - gource
  - grep
  - hostess
  - htop
  - htop-osx
  - iftop
  - jq
  - kompose
  - kubernetes-cli
  - kubernetes-helm
  - kube-ps1
  - logstalgia
  - lolcat
  - mas
  - midnight-commander
  - moreutils
  - mplayer
  - nmap
  - node
  - openssh
  - p7zip
  - pandoc
  - pv
  - rename
  - screen
  - socat
  - ssh-copy-id
  - sshfs
  - sshuttle
  - tcpflow
  - tree
  - unrar
  - watch
  - wget
  - youtube-dl

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - google-chrome
  - macvim
  - slack
  - sublime-text
  - vagrant
  - visual-studio-code
  - virtualbox
  - ubersicht
  - minikube
  - intel-power-gadget
  - hyper

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
- { id: 1295203466, name: "Microsoft Remote Desktop (10.2.6)" }
- { id: 1147396723, name: "WhatsApp (0.3.1850)" }
- { id: 682658836, name: "GarageBand (10.3.2)" }
mas_email: ""
mas_password: ""
mas_signin_dialog: no

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: gtop
    state: present # present/absent/latest, default: present
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

