---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: yes

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false

dotfiles_repo: https://github.com/cmarquezrusso/dotfiles.git
dotfiles_repo_accept_hostkey: yes 
dotfiles_repo_local_destination: ~/dotfiles-ansible
dotfiles_repo_version: main
dotfiles_files:
  - .ssh
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .dockerapps
  - .editorconfig
  - .exports
  - .functions
  - .gdbinit
  - .gitattributes
  - .gitcompletion
  - .gitconfig
  - .gitignore
  - .gvimrc
  - .hgignore
  - .hushlogin
  - .inputrc
  - .kube.tmux
  - .kubectl_aliases
  - .macos
  - .osx
  - .screenrc
  - .tool-versions
  - .tmux.conf
  - .vim
  - .vimrc
  - .wgetrc

homebrew_clear_cache: true
homebrew_installed_packages:
- asciinema
- asdf
- axel
- coreutils
- cowsay
- figlet
- findutils
- git
- git-lfs
- go
- grep
- hostess
- iftop
- jq
- mas
- midnight-commander
- moreutils
- node
- nvm
- p7zip
- pandoc
- screen
- ssh-copy-id
- sshuttle
- tcpflow
- tree
- tmux
- watch
- wget
- youtube-dl

homebrew_uninstalled_packages:
- awscli
- cmatrix
- docker-machine
- docker-machine-driver-hyperkit
- docker-machine-driver-xhyve
- helm@2
- kompose
- minikube
- unrar
- kubernetes-cli
- kubernetes-helm
- kube-ps1
- velero

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adobe-acrobat-reader
  - coconutbattery
  - github
  - google-chrome
  - gpg-suite
  - iina
  - iterm2
  - slack
  - yubico-authenticator
  - yubico-yubikey-manager
  - yubico-yubikey-personalization-gui
  - visual-studio-code
  
homebrew_cask_uninstalled_apps:
  - bitwarden
  - sublime-text
  - google-cloud-sdk
  - docker

mas_installed_apps:
- { id: 1147396723, name: "WhatsApp (0.4.316)" }
- { id: 1352778147, name: "Bitwarden" }
- { id: 682658836, name: "GarageBand (10.3.2)" }
- { id: 408981434, name: "iMovie (10.1.14)" }
- { id: 905953485, name: "NordVPN: VPN Fast & Secure" }
- { id: 803453959, name: "Slack (4.2.0)" }
- { id: 497799835, name: "Xcode (11.3.1)" }

mas_uninstalled_apps:
- { id: 406056744, name: "Evernote (7.14)" }
- { id: 406825478, name: "Telephone (1.4)" }

mas_email: ""
mas_password: ""
mas_signin_dialog: no

#Just the hacker sensitive stuff
osx_script: "~/dotfiles-ansible/.macos" 

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: gtop
    state: present # present/absent/latest, default: present
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"
# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# Set to 'true' to configure p10k
configure_p10k: true

# Powerlevel10k Git repository url
p10k_repository_url: 'https://github.com/romkatv/powerlevel10k.git'

# Install p10k for the following linux users
# Default: the linux user running Ansible
p10k_users:
  - "{{ ansible_user_id }}"

# Zsh plugin used, zsh, ohmyzsh, prezto, Zim, etc..
# All plugin names can be found here https://github.com/romkatv/powerlevel10k#installation
# TODO: Change to OhMyZsh
zsh_plugin: zsh


# Setup p10k theme to use
# Valid values: lean, classic, rainbow, pure
p10k_prompt_style: "rainbow"

# Show current time
# Valid values: no, 24-hour, 12-hour
p10k_prompt_time: "24-hour"

# Prompt sperator
# Valid values: angled, vertical, slanted, round
p10k_prompt_separator: "angled"

# Prompt heads
# Valid values: sharp, blurred, slanted, round
p10k_prompt_head: "sharp"

# Prompt tails
# Valid values: flat, blurred, sharp, slanted, round
p10k_prompt_tails: flat

# Terminal prompt height
# Valid values: one-line, two-lines
p10k_prompt_height: two-lines

# Prompt connection, only used if "p10k_prompt_height" value is "two-lines"
# Valid values: disconnected, dotted, solid
p10k_prompt_connection: disconnected

# Prompt connection color, only used if
# "p10k_prompt_connection" value is "dotted" or "solid"
# or "p10k_prompt_frame" is not "no"
# Valid values: lightest, light, dark, darkest, black, white, green, blue
p10k_prompt_connection_color: "dark"

# Prompt frame connection
# Valid values: no, left, right, full
p10k_prompt_frame: left

# Sparse prompt with an empty line before promp
# Valid values: compact, sparse
p10k_prompt_spacing: compact

# Terminal flow
# Valid values: concise, fluent
p10k_prompt_flow: concise

# Enable transient prompt
# Valid values: yes, no
p10k_transient_prompt: "no"