---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  #- autoconf
  - bash-completion
  #- doxygen
  #- gettext
  #- gifsicle
  - git
  - go
  #- gpg
  #- hub
  #- httpie
  #- iperf
  #- libevent
  #- sqlite
  #- mcrypt
  - nmap
  - node
  - nvm
  #- php
  - ssh-copy-id
  - cowsay
  #- readline
  #- openssl
  #- pv
  - wget
  #- wrk
  # Mine
  #- arp-scan
  - asciinema
  #- asdf
  #- awscli
  - axel
  - binwalk
  - cmatrix
  - coreutils
  - cowsay
  #- docker-machine
  #- docker-machine-driver-xhyve
  - ext4fuse
  - ffmpeg
  - figlet
  #- flow
  #- fontconfig
  - fortune
  #- gettext
  #- git
  - gnuplot
  #- go
  - gource
  - htop
  - htop-osx
  #- icu4c
  - iftop
  - jq
  - kompose
  - kubectx
  #- kubeless
  - kubernetes-cli
  - kubernetes-helm
  - logstalgia
  - lolcat
  - mas
  - midnight-commander
  - mplayer
  - nmap
  - ntfs-3g
  - rdesktop
  - rkhunter
  - sshfs
  - sshuttle
  - sslscan
  - stress
  - tcpflow
  - telnet
  - terraform
  - thefuck
  - tmux
  - tree
  - unrar
  - vault
  - vegeta
  - watch
  - wget
  - youtube-dl

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - google-chrome
  - handbrake
  - licecap
  - limechat
  - macvim
  - sequel-pro
  - skitch
  - slack
  - sublime-text
  - vagrant

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
- { id: 1295203466, name: "Microsoft Remote Desktop (10.2.6)" }
- { id: 1147396723, name: "WhatsApp (0.3.1850)" }
mas_email: ""
mas_password: ""
mas_signin_dialog: no


osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
